events {}
http {
  server {
    listen 80; 
    
    # Все запросы на обычные страницы отправляем во Фронтенд
    location / {
      proxy_pass http://frontend:3000;
    }
    
    # Все запросы, которые начинаются с /api, отправляем в Бэкенд
    location /api {
      proxy_pass http://backend:5000;
    }
  }
}
